### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by zjpleau** [zaggash/docker-transmission#1]
Hey there,

I found this from [another post](https://github.com/linuxserver/docker-nzbget/issues/18) you made about getting ffmpeg to work within nzbget but I'm not sure where to start.  Could you possibly share some instructions?

Thanks!

**Comment by zaggash** [comment]
Sure, I let you know asap during the day.

**Comment by zaggash** [comment]
First of all I made it working for Transmission.
But it is the same for nzbget.

Actually, I created my own Transmission Dockerfile from Linuxserver.io image and added the nzbtomedia application with my own packages.
This can be done for nzbget as well.

I can send you a gist if you need some insight to begin with.

**Comment by zaggash** [comment]
I close this one. 
Feel free to reopen if you need more informations.
