### ISSUE TITLE
where to find torrentomedia.py ?

### ISSUE THREAD

**Issue by flovanc** [zaggash/docker-transmission#6]

**Comment by zaggash** [comment]
The file is in the container :  /app/nzbToMedia
You can access it with  :  docker exec -ti <container_name_or_id> bash

**Comment by flovanc** [comment]
Oh thanks ... I try this Yesterday evening and there was nothing inside app/nzbToMedia/ 
 
But now i found the files . The git extract inside the container is maybe slow ?

By the way thanks for the work and quick answers 

Flo

**Comment by zaggash** [comment]
Yeah depends on you connection, it can take a minute ;)

**Comment by flovanc** [comment]
Oh!! I remove container and make a new install off container whit docker-compose.yml . And one hour After i have only autoProcessMedia.cfg file and logs folder inside app/nzbToMedia of the container !!!

Must i have to wait or there is somthing wrong ?

Flo


edit: all is working perfectly ;o)

just a mistake whit a volume from my docker-compose.yml file .
can't have
`volumes:
      - ${USERDIR}/docker/transmission:/app/nzbToMedia 
`
this overwrite the /app/nzbToMedia

 

```
